# Recurrent Neural Network
- mathematical experession
$$P(x_t|x_{t-1},..,x_1) \approx P(x_t|h_{t-1})$$
$$ h_t = f(x_t, h_{t-1}) $$

- Neural Network Hidden state
$$ H = \phi(XW_{xh} + b_h)$$

In [1]:
import torch
from d2l import torch as d2l

X, W_xh = torch.normal(0, 1, (3, 1)), torch.normal(0, 1, (1, 4)) # x는 3,1의 벡터고 weight는 1,4의 weight
H, W_hh = torch.normal(0, 1, (3, 4)), torch.normal(0, 1, (4, 4))
torch.matmul(X, W_xh) + torch.matmul(H, W_hh) # output

tensor([[-0.9444, -0.8728,  0.1801, -1.7676],
        [-1.4616, -0.3225, -0.2576, -1.2187],
        [-1.5597, -0.7058,  0.1005, -0.1664]])

위와 같은 상황을 선형대수적으로 표현할 경우 아래처럼 concat을 해서 표현할 수 있을 것이다.

In [2]:
torch.matmul(torch.cat((X, H), 1), torch.cat((W_xh, W_hh), 0)) 

tensor([[-0.9444, -0.8728,  0.1801, -1.7676],
        [-1.4616, -0.3225, -0.2576, -1.2187],
        [-1.5597, -0.7058,  0.1005, -0.1664]])

Implementation of RNN

In [4]:
import math
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

batch_size, num_steps = 32, 35
train_iter, vocab = d2l.load_data_time_machine(batch_size, num_steps) # load time machine data

In [5]:
# one hot encoding
# match each index to unit vector

F.one_hot(torch.tensor([0, 2]), len(vocab)) # one hot vector for index 0 and 2

tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0]])

In [8]:
X = torch.arange(10).reshape((2, 5))
F.one_hot(X.T, 28).shape # 5,2,28 차원으로 바뀌었다. 
# 0,1,2,3 ..은 index이고
# index에 따라서?

torch.Size([5, 2, 28])